# Generated by Django 3.2.5 on 2021-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('field', models.CharField(choices=[('BIT', 'BIT'), ('BBA', 'BBA'), ('MSCIT', 'MSCIT'), ('CSIT', 'CSIT')], max_length=70)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
